export const FETCH_HERO_LOADING = 'FETCH_HERO_LOADING';
export const FETCH_HERO_NOT_LOADING = 'FETCH_HERO_NOT_LOADING';
export const FETCH_HERO_SUCCESS = 'FETCH_HERO_SUCCESS';
export const FETCH_HERO_ERROR = 'FETCH_HERO_ERROR';
export const RESET_HERO = 'RESET_HERO';
export const UPDATE_FAVORITE_HERO = 'UPDATE_FAVORITE_HERO';
export const UPDATE_FAVORITE_HERO_SUCCESS = 'UPDATE_FAVORITE_HERO_SUCCESS';
