export const FETCH_HEROS_LOADING = 'FETCH_HEROS_LOADING';
export const FETCH_HEROS_NOT_LOADING = 'FETCH_HEROS_NOT_LOADING';
export const FETCH_HEROS_SUCCESS = 'FETCH_HEROS_SUCCESS';
export const FETCH_HEROS_ERROR = 'FETCH_HEROS_ERROR';
export const UPDATE_HEROS = 'UPDATE_HEROS';
